### PR TITLE
Add jQuery Migrate to fix diff dialog

### LINKED ISSUE #36: diff dialog not working with Notebook 5.6.0
The following error occurs.

```
Uncaught TypeError: r.getClientRects is not a function
    at w.fn.init.offset (main.min.js:2)
    at Object.getWithinInfo (main.min.js:46149)
    at w.fn.init.t.fn.position (main.min.js:46149)
    at t.(anonymous function).(anonymous function)._position (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46150:14716)
    at t.(anonymous function).(anonymous function)._position (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46149:5029)
    at t.(anonymous function).(anonymous function).open (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46150:6534)
    at t.(anonymous function).(anonymous function).open (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46149:5029)
    at t.(anonymous function).(anonymous function)._init (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46150:5169)
    at t.(anonymous function).(anonymous function)._init (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46149:5029)
    at t.(anonymous function).(anonymous function)._createWidget (http://localhost:8090/static/notebook/js/main.min.js?v=822e8e7f056ebad0ff240a742d277487:46149:7107)
```
I assume that jquery-ui 1.10.4 is not compatible with jquery 3.3.1.
Jupyter Notebook prior to 5.6.0 use jquery 2.x, 5.6.0 use jquery 3.3.x.
- https://github.com/jupyter/notebook/blob/5.5.0/bower.json#L13
- https://github.com/jupyter/notebook/blob/5.6.0/bower.json#L13

I assume that adding jquery-migrate-3.0.0.js resolves this issue.
- http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/
- https://stackoverflow.com/questions/37914869/jquery-ui-error-f-getclientrects-is-not-a-function

### PR DESCRIPTION
**Pull request by shingo78**
Fix #36 

This workaround should be removed when jQuery UI included in Jupyter Notebook is upgraded.

### CODE REVIEW

**Review by yacchin1205 — APPROVED** [review]
LGTM . I'll merge this PR.
